spring:
  main:
    show_banner: false

reksio:
  awake: true
  bornIn: Poland
  birthYear: 1967
  friends:
    - Bolek
    - Lolek

  homepage: https://en.wikipedia.org/wiki/Reksio
  grades: Math=A,PE=A,Polish=A

some:
  setting: some setting string value
  other:
    setting: what do you know? :p